package model;
// Generated 2017-10-29 14:32:57 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name = "teacher", catalog = "usermanager")
public class Teacher{

	private Integer id;
	private String tname;
	private String tpass;

	public Teacher() {
	}

	public Teacher(String tname, String tpass) {
		this.tname = tname;
		this.tpass = tpass;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tName", length = 30)
	public String getTname() {
		return this.tname;
	}

	public void setTname(String tname) {
		this.tname = tname;
	}

	@Column(name = "tPass", length = 30)
	public String getTpass() {
		return this.tpass;
	}

	public void setTpass(String tpass) {
		this.tpass = tpass;
	}

	@Override
	public String toString() {
		return "Teacher [id=" + id + ", tname=" + tname + ", tpass=" + tpass + "]";
	}

}
